# Generated by Django 5.2.10 on 2026-01-30 07:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0002_permission_role_rolepermission_userroleassignment"),
        ("users", "0002_alter_user_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="employee",
            name="aadhaar_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="employee",
            name="account_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="blood_group",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="employee",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="confirmation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="country",
            field=models.CharField(default="India", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="current_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="current_ctc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_joining",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_relation",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_code",
            field=models.CharField(default="EMP000", max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PROBATION", "Probation"),
                    ("NOTICE", "Notice Period"),
                    ("RESIGNED", "Resigned"),
                    ("TERMINATED", "Terminated"),
                    ("RETIRED", "Retired"),
                ],
                default="PROBATION",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("PERMANENT", "Permanent"),
                    ("CONTRACT", "Contract"),
                    ("INTERN", "Intern"),
                    ("CONSULTANT", "Consultant"),
                    ("PART_TIME", "Part Time"),
                ],
                default="PERMANENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SINGLE", "Single"),
                    ("MARRIED", "Married"),
                    ("DIVORCED", "Divorced"),
                    ("WIDOWED", "Widowed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="employee",
            name="pan_number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="employee",
            name="permanent_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="personal_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="employee",
            name="pincode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="employee",
            name="reporting_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportees",
                to="hrms.employee",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="uan_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="employee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("tenant", "employee_code")},
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PHOTO", "Photograph"),
                            ("RESUME", "Resume/CV"),
                            ("AADHAAR", "Aadhaar Card"),
                            ("PAN", "PAN Card"),
                            ("PASSPORT", "Passport"),
                            ("DEGREE", "Educational Certificate"),
                            ("EXPERIENCE", "Experience Letter"),
                            ("OFFER", "Offer Letter"),
                            ("APPOINTMENT", "Appointment Letter"),
                            ("SALARY_SLIP", "Salary Slip"),
                            ("RELIEVING", "Relieving Letter"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="employee_documents/%Y/%m/")),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hrms.employee",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100)),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        default="INTERMEDIATE",
                        max_length=20,
                    ),
                ),
                (
                    "years_of_experience",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                ("certification_name", models.CharField(blank=True, max_length=200)),
                (
                    "certification_authority",
                    models.CharField(blank=True, max_length=200),
                ),
                ("certification_date", models.DateField(blank=True, null=True)),
                ("certification_expiry_date", models.DateField(blank=True, null=True)),
                ("certification_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="hrms.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-proficiency", "-years_of_experience"],
            },
        ),
    ]
