# Generated by Django 5.2.10 on 2026-01-30 09:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0005_alter_attendance_options_attendance_created_at_and_more"),
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leave",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AddField(
            model_name="leave",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leave",
            name="number_of_days",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name="leave",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("default_days_per_year", models.IntegerField(default=12)),
                ("is_paid", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=True)),
                ("max_consecutive_days", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_types",
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "total_allocated",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                (
                    "used",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "pending",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("available", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "carried_forward",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="hrms.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="hrms.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "leave_type"],
                "unique_together": {("employee", "leave_type", "year")},
            },
        ),
    ]
