# Generated by Django 5.2.10 on 2026-01-30 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0006_alter_leave_options_leave_approved_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to="hrms.leavetype",
            ),
        ),
    ]
