# Generated by Django 4.0 on 2026-01-30 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_groups_alter_user_user_permissions'),
        ('hrms', '0008_payrollrun_payslip_salarycomponent_salarystructure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_cycles', to='users.tenant')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('WORK', 'Work'), ('DEVELOPMENT', 'Personal Development')], default='WORK', max_length=20)),
                ('weightage', models.IntegerField(default=0, help_text='Weightage in percentage (0-100)')),
                ('progress', models.IntegerField(default=0, help_text='Completion percentage (0-100)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='hrms.appraisalcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='hrms.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('self_comments', models.TextField(blank=True, help_text="Employee's self-reflection")),
                ('manager_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('final_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('final_comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (Self)'), ('SELF_SUBMITTED', 'Self Review Submitted'), ('MANAGER_REVIEW', 'Manager Reviewing'), ('HR_REVIEW', 'HR Reviewing'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hrms.appraisalcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hrms.employee')),
                ('reviewer', models.ForeignKey(help_text='The manager doing the review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reviews', to='hrms.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant')),
            ],
            options={
                'unique_together': {('employee', 'cycle')},
            },
        ),
    ]
