# Generated by Django 4.0 on 2026-01-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_groups_alter_user_user_permissions'),
        ('hrms', '0009_appraisalcycle_goal_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Model name or description', max_length=200)),
                ('serial_number', models.CharField(help_text='Unique Serial Number / License Key', max_length=100)),
                ('asset_id', models.CharField(blank=True, help_text='Internal Tag ID (optional)', max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('IN_REPAIR', 'In Repair'), ('SCRAPPED', 'Scrapped'), ('LOST', 'Lost')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='users.tenant')),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AssetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('returned_condition', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Currently held by employee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hrms.asset')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_assigned_by', to='users.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_held', to='hrms.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='hrms.assetcategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='users.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('tenant', 'serial_number')},
        ),
    ]
