# Generated by Django 4.0 on 2026-02-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_employeeexperience_employeeeducation_employeebgv'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='temp_password',
            field=models.CharField(blank=True, help_text='Temporary password for initial login', max_length=50, null=True),
        ),
    ]
