# Generated by Django 4.0 on 2026-02-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_tenant_options_alter_user_options_and_more'),
        ('hrms', '0019_taxdeclaration_admin_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=True, help_text='Does this holiday repeat every year?')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='users.tenant')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('tenant', 'date')},
            },
        ),
    ]
