# Generated by Django 4.0 on 2026-02-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0020_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='allow_reentry',
            field=models.BooleanField(default=False, help_text='Allow employees to punch in again after punching out on the same day'),
        ),
    ]
