# Generated by Django 4.0 on 2026-02-04 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0021_attendancepolicy_allow_reentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrms.shift'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LATE', 'Late'), ('ON_LEAVE', 'On Leave'), ('WEEK_OFF', 'Week Off'), ('HOLIDAY', 'Holiday')], default='PRESENT', max_length=20),
        ),
    ]
