# Generated by Django 4.0 on 2026-02-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0023_alter_employee_designation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='role',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='role',
        ),
        migrations.AlterUniqueTogether(
            name='userroleassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userroleassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='userroleassignment',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userroleassignment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.DeleteModel(
            name='UserRoleAssignment',
        ),
    ]
