# Generated by Django 4.0 on 2026-02-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0024_alter_role_unique_together_remove_role_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducation',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_records', to='hrms.employeedocument'),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_records', to='hrms.employeedocument'),
        ),
    ]
