# Generated by Django 4.0 on 2026-01-31 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_employeeexperience_employeeeducation_employeebgv'),
        ('crm', '0002_alter_client_options_alter_interaction_options_and_more'),
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['name'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock Transaction', 'verbose_name_plural': 'Stock Transactions'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', '-id'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, help_text='Item description'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(help_text='Item name', max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity_on_hand',
            field=models.IntegerField(default=0, help_text='Current stock level'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.IntegerField(default=10, help_text='Minimum quantity before reordering'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(help_text='Stock Keeping Unit', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Associated client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Expected/actual completion date', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Project manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='hrms.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Project name/title', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(help_text='Project start date'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.IntegerField(help_text='Number of units'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='reason',
            field=models.TextField(blank=True, help_text='Transaction reason/notes'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], help_text='IN (received) or OUT (issued)', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Assigned employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='hrms.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed task description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Task deadline', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Task title', max_length=200),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant', 'sku'], name='erp_invento_tenant__d9aedc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant', 'quantity_on_hand'], name='erp_invento_tenant__fb7817_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'status'], name='erp_project_tenant__0b9146_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['manager'], name='erp_project_manager_356623_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client'], name='erp_project_client__aa1e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['item', '-created_at'], name='erp_stocktr_item_id_c400b8_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['tenant', 'transaction_type'], name='erp_stocktr_tenant__2e37da_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='erp_task_project_12020d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='erp_task_assigne_9dbd2e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='erp_task_due_dat_ddb0b5_idx'),
        ),
    ]
