# Generated by Django 4.0 on 2026-01-31 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_tenant_options_alter_user_options_and_more'),
        ('hrms', '0016_employeeexperience_employeeeducation_employeebgv'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Interaction', 'verbose_name_plural': 'Interactions'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(help_text='Primary contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, help_text='Business industry/sector', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Client/company name', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='tenant',
            field=models.ForeignKey(help_text='Organization this client belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='users.tenant'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='summary',
            field=models.TextField(help_text='Interaction summary/notes'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Assigned salesperson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='hrms.employee'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='expected_close_date',
            field=models.DateField(blank=True, help_text='Expected closing date', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='probability',
            field=models.IntegerField(default=0, help_text='Win probability (0-100%)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='title',
            field=models.CharField(help_text='Lead title/description', max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated deal value', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', '-created_at'], name='crm_client_tenant__f72faf_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='crm_client_email_3c7615_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['lead', '-created_at'], name='crm_interac_lead_id_4e14dd_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'stage'], name='crm_lead_tenant__fb8c89_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='crm_lead_assigne_2d9eb1_idx'),
        ),
    ]
