# Generated by Django 4.0 on 2026-02-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='currency',
            field=models.CharField(default='USD', help_text='Default currency for the tenant', max_length=3),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_setup_complete',
            field=models.BooleanField(default=False, help_text='Whether the tenant has completed onboarding'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarding_step',
            field=models.IntegerField(default=1, help_text='Current step in onboarding process'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status_actions',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for employee status actions'),
        ),
    ]
